# Generated by Django 5.1.7 on 2025-06-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0023_alter_userprofile_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
