# Generated by Django 5.1.7 on 2025-03-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
