# Generated by Django 5.1.7 on 2025-03-31 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_for', models.CharField(max_length=50)),
                ('int_date', models.DateField(default=datetime.date.today)),
                ('referred', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=70, null=True)),
                ('emp_id', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=30)),
                ('r_shift', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=70, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('bgv_link', models.IntegerField(default=0)),
                ('bgv_sent_on', models.DateField(null=True)),
                ('bgv_received_on', models.DateField(null=True)),
                ('doc_link', models.IntegerField(default=0)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='hrmsApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school', models.CharField(max_length=30, null=True)),
                ('intermediate', models.CharField(max_length=30, null=True)),
                ('diploma', models.CharField(max_length=30, null=True)),
                ('pg', models.CharField(max_length=30, null=True)),
                ('master', models.CharField(max_length=30, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_candidate', to='hrmsApp.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_level', models.CharField(max_length=30)),
                ('exp_year', models.CharField(max_length=30, null=True)),
                ('exp_month', models.CharField(max_length=30, null=True)),
                ('curr_month_salary', models.CharField(max_length=30, null=True)),
                ('curr_year_salary', models.CharField(max_length=30, null=True)),
                ('expec_month_salary', models.CharField(max_length=30, null=True)),
                ('notice_period', models.CharField(max_length=30, null=True)),
                ('resume', models.CharField(max_length=70, null=True)),
                ('portfolio', models.CharField(max_length=70, null=True)),
                ('links', models.CharField(max_length=255, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_candidate', to='hrmsApp.candidate')),
            ],
        ),
    ]
