# Generated by Django 5.1.7 on 2025-03-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0006_jobrole_alter_candidate_apply_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
