# Generated by Django 5.1.7 on 2025-03-31 08:04

import hrmsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0007_candidate_source_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_portfolio_path),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_resume_path),
        ),
    ]
