# Generated by Django 5.1.7 on 2025-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0008_education_graduation_alter_experience_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='token',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
