# Generated by Django 5.1.7 on 2025-04-01 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0010_alter_candidate_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_mode', models.CharField(max_length=30)),
                ('int_date', models.DateField(blank=True, null=True)),
                ('int_time', models.CharField(blank=True, max_length=30, null=True)),
                ('int_round', models.IntegerField(default=0, help_text='0=>Assign to HR | 1=>HR Remarked | 2=>Assign to TL | 3=> TL Remarked | 4=>Assign to Manager | 5=>Manager Remarked | 6=>Final Remarked | 7=>BGB Remarked')),
                ('assign_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_from', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_candidate', to='hrmsApp.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=30)),
                ('re_status', models.CharField(max_length=70)),
                ('remark', models.TextField(null=True)),
                ('assigned_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_candidate', to='hrmsApp.assign')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_to_cand', to='hrmsApp.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_exe', models.IntegerField()),
                ('applicable_skl', models.IntegerField()),
                ('appearance', models.IntegerField()),
                ('attiude', models.IntegerField()),
                ('education', models.IntegerField()),
                ('enthusiasm', models.IntegerField()),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_info', to='hrmsApp.remark')),
            ],
        ),
    ]
