# Generated by Django 5.1.7 on 2025-04-03 05:29

import django.db.models.deletion
import hrmsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0012_alter_assign_assign_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bgv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('leaving_resason', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_candidate', to='hrmsApp.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Bgv_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_latter', models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_dgv_doc_path)),
                ('relieving_latter', models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_dgv_doc_path)),
                ('exp_certificate', models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_dgv_doc_path)),
                ('salary_slip0', models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_dgv_doc_path)),
                ('salary_slip1', models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_dgv_doc_path)),
                ('salary_slip2', models.FileField(blank=True, null=True, upload_to=hrmsApp.models.upload_dgv_doc_path)),
                ('bgv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_doc', to='hrmsApp.bgv')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_doc_candidate', to='hrmsApp.candidate')),
            ],
        ),
    ]
