# Generated by Django 5.1.7 on 2025-04-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0013_bgv_bgv_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgv',
            old_name='leaving_resason',
            new_name='leaving_reason',
        ),
    ]
