# Generated by Django 5.1.7 on 2025-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0014_rename_leaving_resason_bgv_leaving_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgv',
            name='hr_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
