# Generated by Django 5.1.7 on 2025-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0015_alter_bgv_hr_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgv',
            name='manager_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
