# Generated by Django 5.1.7 on 2025-04-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0016_alter_bgv_manager_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_d', to='hrmsApp.candidate'),
        ),
    ]
