# Generated by Django 5.1.7 on 2025-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0018_candidate_designation_candidate_doj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cand_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
