# Generated by Django 5.1.7 on 2025-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0019_candidate_cand_status_alter_candidate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
