# Generated by Django 5.1.7 on 2025-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0020_alter_candidate_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cand_status',
            field=models.IntegerField(default=0, help_text='0=>In Process | 1=>Rejected | 2=>On board'),
        ),
    ]
