# Generated by Django 5.1.7 on 2025-06-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsApp', '0022_designations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designations',
        ),
    ]
